splits:
    - prefix: "src/bundle"
      target: "https://${GH_TOKEN}@github.com/scheb/2fa-bundle.git"
    - prefix: "src/email"
      target: "https://${GH_TOKEN}@github.com/scheb/2fa-email.git"
    - prefix: "src/google-authenticator"
      target: "https://${GH_TOKEN}@github.com/scheb/2fa-google-authenticator.git"
    - prefix: "src/totp"
      target: "https://${GH_TOKEN}@github.com/scheb/2fa-totp.git"
    - prefix: "src/backup-code"
      target: "https://${GH_TOKEN}@github.com/scheb/2fa-backup-code.git"
    - prefix: "src/trusted-device"
      target: "https://${GH_TOKEN}@github.com/scheb/2fa-trusted-device.git"
    - prefix: "src/qr-code"
      target: "https://${GH_TOKEN}@github.com/scheb/2fa-qr-code.git"
    - prefix: "src/webauthn"
      target: "https://${GH_TOKEN}@github.com/scheb/2fa-webauthn.git"

origins:
    - ^[0-9]+\.x$
    - ^v\d+\.\d+$
    - ^v\d+\.\d+\.\d+.*$
