filter:
    paths:
        - src/
    dependency_paths:
        - vendor/
build:
    environment:
        php:
            version: 8.0
    dependencies:
        override:
            - composer install --ignore-platform-reqs --no-interaction
    tests:
        override:
            - php-scrutinizer-run
tools:
    external_code_coverage: true
