filter:
    paths:
        - src/
    dependency_paths:
        - vendor/
build:
    environment:
        php:
            version: 7.4
    tests:
        override:
            - php-scrutinizer-run
tools:
    external_code_coverage: true
