name: 'Setup Build'
description: 'Setup the build for this project'
inputs:
    php-version:
        description: 'PHP version to use'
        required: true
    php-coverage:
        description: 'Code coverage tool for php'
        required: false
        default: 'none'
    composer-token:
        description: 'Github token for Composer'
        required: true
    composer-working-dir:
        description: 'Composer working directory'
        required: false
        default: '.'
    composer-require:
        description: 'Additional Composer dependencies to be added'
        required: false
        default: ''
    composer-allow-dev:
        description: 'If Composer should allow dev dependencies to be used'
        required: false
        default: ''
    composer-dependency-versions:
        description: 'Whether the job should install the locked, highest, or lowest versions of Composer dependencies'
        required: false
        default: ''
    symfony-version:
        description: 'Symfony version to be installed'
        required: false
        default: ''
runs:
    using: "composite"
    steps:
        -   name: 'Setup PHP'
            uses: shivammathur/setup-php@v2
            with:
                coverage: '${{ inputs.php-coverage }}'
                php-version: '${{ inputs.php-version }}'
                tools: php-cs-fixer
            env:
                COMPOSER_TOKEN: ${{ inputs.composer-token }}

        -   name: 'Display PHP versions'
            shell: bash
            run: |
                php -r 'foreach (get_loaded_extensions() as $extension) echo $extension . " " . phpversion($extension) . PHP_EOL;'
                php -i

        -   name: "Composer allow dev dependencies"
            if: ${{ inputs.composer-allow-dev }}
            shell: bash
            run: composer config minimum-stability dev && composer config prefer-stable true --working-dir=${{ inputs.composer-working-dir }}

        -   name: "Install Flex to require specific Symfony version"
            if: ${{ inputs.symfony-version }}
            shell: bash
            run: |
                composer global require --no-progress --no-scripts --no-plugins symfony/flex
                composer global config --no-plugins allow-plugins.symfony/flex true

        -   name: "Require extra Composer dependencies"
            if: ${{ inputs.composer-require }}
            shell: bash
            run: composer require ${{ inputs.composer-require }} --dev --no-update --working-dir=${{ inputs.composer-working-dir }}

        -   name: "Remove Psalm from dependencies"
            shell: bash
            run: composer remove --dev vimeo/psalm

        -   name: "Validate composer.json"
            shell: bash
            run: composer validate --no-check-publish --no-check-lock --working-dir=${{ inputs.composer-working-dir }}

        -   name: 'Install Composer dependencies'
            uses: ramsey/composer-install@v2
            env:
                SYMFONY_REQUIRE: ${{ inputs.symfony-version }}
            with:
                composer-options: '--prefer-dist --working-dir=${{ inputs.composer-working-dir }}'
                dependency-versions: '${{ inputs.composer-dependency-versions }}'

        -   name: 'Display dependencies versions'
            shell: bash
            run: composer show --working-dir=${{ inputs.composer-working-dir }}
