name: 'Split Release'

on:
    release:
        types:
            - published

jobs:
    split:
        name: 'Split sub-packages'

        runs-on: 'ubuntu-latest'

        steps:
            -
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0  # Fetch all history
                    ref: "6.x" # Force checkout the branch to split its commits as well

            -
                name: "Gitsplit"
                uses: docker://jderusse/gitsplit:latest
                with:
                    args: gitsplit
                env:
                    GH_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
